
name: adinath_iptv
description: IPTV Player App
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  video_player: ^2.8.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
